[2019-12-16 17:39:08 +0000] [115891] [DEBUG] Current configuration:
  config: None
  bind: [':5201']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /nfs/gns/literature/Santosh_Tirunagari/GitHub/Unsupervised-Protein-Genes-Diseases-Extraction/Micro_Services
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 8623
  group: 1057
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: access.txt
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: log.txt
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  statsd_prefix: 
  proc_name: None
  default_proc_name: PCSE_ner_server:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x2b742c1b4dd0>
  on_reload: <function OnReload.on_reload at 0x2b742c1b4ef0>
  when_ready: <function WhenReady.when_ready at 0x2b742c1c7050>
  pre_fork: <function Prefork.pre_fork at 0x2b742c1c7170>
  post_fork: <function Postfork.post_fork at 0x2b742c1c7290>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x2b742c1c73b0>
  worker_int: <function WorkerInt.worker_int at 0x2b742c1c74d0>
  worker_abort: <function WorkerAbort.worker_abort at 0x2b742c1c75f0>
  pre_exec: <function PreExec.pre_exec at 0x2b742c1c7710>
  pre_request: <function PreRequest.pre_request at 0x2b742c1c7830>
  post_request: <function PostRequest.post_request at 0x2b742c1c78c0>
  child_exit: <function ChildExit.child_exit at 0x2b742c1c79e0>
  worker_exit: <function WorkerExit.worker_exit at 0x2b742c1c7b00>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x2b742c1c7c20>
  on_exit: <function OnExit.on_exit at 0x2b742c1c7d40>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: TLSv1
  raw_paste_global_conf: []
[2019-12-16 17:39:08 +0000] [115891] [INFO] Starting gunicorn 19.9.0
[2019-12-16 17:39:08 +0000] [115891] [DEBUG] Arbiter booted
[2019-12-16 17:39:08 +0000] [115891] [INFO] Listening at: http://0.0.0.0:5201 (115891)
[2019-12-16 17:39:08 +0000] [115891] [INFO] Using worker: sync
[2019-12-16 17:39:08 +0000] [115918] [INFO] Booting worker with pid: 115918
[2019-12-16 17:39:08 +0000] [115891] [DEBUG] 1 workers
[2019-12-16 17:39:08 +0000] [115918] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/homes/stirunag/anaconda3/envs/pytorch/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/homes/stirunag/anaconda3/envs/pytorch/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/homes/stirunag/anaconda3/envs/pytorch/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/homes/stirunag/anaconda3/envs/pytorch/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/homes/stirunag/anaconda3/envs/pytorch/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/homes/stirunag/anaconda3/envs/pytorch/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/homes/stirunag/anaconda3/envs/pytorch/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'PCSE_ner_server'
[2019-12-16 17:39:08 +0000] [115918] [INFO] Worker exiting (pid: 115918)
[2019-12-16 17:39:08 +0000] [115891] [INFO] Shutting down: Master
[2019-12-16 17:39:08 +0000] [115891] [INFO] Reason: Worker failed to boot.
